version: "3.9"
services:
  db:
    hostname: postgres
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=bob
      - POSTGRES_PASSWORD=mypasswd
      - POSTGRES_DB=prove
    ports:
      - "5435:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data
    networks:
      - mynet
  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_PLUGINS: "tables-filter tinymce"
      ADMINER_DEFAULT_SERVER: "postgres"
    #      ADMINER_DESIGN: "nette"
    ports:
      - "8077:8080"
    networks:
      - mynet
  prove:
    image: setter2000/prove
    environment:
      DATABASE_URI: "postgres://bob:mypasswd@db:5432/prove?sslmode=disable"
    container_name: "prove"
    command: ./prove
    ports:
      - "8080:8080"
#      - "443:443"
    restart: always
    networks:
      - mynet
volumes:
  prove-data:
networks:
  mynet:
    driver: bridge