app:
  name: 'prove'
  access_token_name: 'user_id'
cookie:
  secret_key: 'erter09gj0f9g'
  access_token_name: 'access_token'
http:
#  port: '8080'
#  base_url: 'http://localhost:8080'
logger:
  log_level: 'debug'
  rollbar_env: 'prove'